version: '3.9'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - node.name=es01
      - cluster.name=single-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - path.repo=/usr/share/elasticsearch/snapshots
    ports:
      - "9200:9200"
    volumes:
      - ./esdata/single:/usr/share/elasticsearch/data
      - ./es_snapshots:/usr/share/elasticsearch/snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1